
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crowdaxcore_development
  host: localhost
  username: crowdax
  password: ihatepass

test:
  <<: *default
  database: crowdaxcore_test
  host: localhost
  username: crowdax
  password: ihatepass


production:
  <<: *default
  database: crowdaxcore_production
  username: crowdaxcore
  password: <%= ENV['CROWDAXCORE_DATABASE_PASSWORD'] %>
